# Generated by Django 4.0.3 on 2022-03-30 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ususario',
            new_name='Usuario',
        ),
    ]
