# Generated by Django 4.0.3 on 2022-03-30 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0002_rename_ususario_usuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commentario',
            new_name='Comentario',
        ),
    ]
