# Generated by Django 4.0.3 on 2022-03-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0003_rename_commentario_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='creador',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
