# Generated by Django 4.0.3 on 2022-04-28 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0007_remove_comentario_auto_increment_id_comentario_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='id',
        ),
        migrations.AddField(
            model_name='comentario',
            name='auto_increment_id',
            field=models.AutoField(default=123, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
