# Generated by Django 4.0.3 on 2022-04-28 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0008_remove_comentario_id_comentario_auto_increment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='auto_increment_id',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False),
        ),
    ]
