# Generated by Django 4.0.3 on 2022-04-28 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0009_remove_comentario_auto_increment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='auto_increment_id',
            field=models.AutoField(default=20000223, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
