# Generated by Django 4.0.3 on 2022-04-28 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0011_remove_comentario_auto_increment_id_comentario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
