# Generated by Django 4.0.3 on 2022-05-02 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0014_alter_avatar_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
