# Generated by Django 4.0.3 on 2022-04-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=200)),
                ('destinatario', models.CharField(max_length=40)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creador', models.CharField(max_length=40)),
            ],
        ),
    ]
